apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    pc-deployment-backend
  labels:
      app: pc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pc-deployment
      tier: backend
  template:
    metadata:
      labels:
        app: pc-deployment
        tier: backend
        version: 0.0.2
    spec:
      containers:
      - name: producer
        image: docker.io/library/producer-image:0.0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    pc-deployment-front
  labels:
      app: pc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pc-deployment
      tier: frontend
  template:
    metadata:
      labels:
        app: pc-deployment
        tier: frontend
    spec:
      containers:
      - name: consumer
        image: docker.io/library/consumer-image:0.0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pc-service
  labels:
      app: pc-deployment
spec:
  selector:
    app: pc-deployment
    tier: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pc-nodeport
  labels:
      app: pc-deployment
spec:
  selector:
    app: pc-deployment
    tier: frontend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007
  type: NodePort
