apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    pc-deployment-backend
  labels:
      app: pc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pc-deployment
      tier: backend
  template:
    metadata:
      labels:
        app: pc-deployment
        tier: backend
    spec:
      containers:
      - name: producer
        image: docker.io/library/producer-image:0.0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    pc-deployment-front
  labels:
      app: pc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pc-deployment
      tier: frontend
  template:
    metadata:
      labels:
        app: pc-deployment
        tier: frontend
    spec:
      containers:
      - name: consumer
        image: docker.io/library/consumer-image:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000